services:
  postgres:
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: Langgraph
    ports:
      - "5442:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data  # add this

volumes:
  postgres_data:  # This is just the name of the volumne in a container